import Head from "next/head";
import { FC } from "react";

import styles from "../styles/Home.module.css";

const redirectUrl = `${
  process.env.NEXT_PUBLIC_HOST || "http://localhost:3000"
}/github`;

const Home: FC = () => {
  const handleLoginWithGithub = () => {
    if (!process.env.NEXT_PUBLIC_GITHUB_APP_CLIENT_ID) {
      console.info("cannot redirect to github auth page");
      return;
    }

    window.location.assign(
      `https://github.com/login/oauth/authorize?client_id=${process.env.NEXT_PUBLIC_GITHUB_APP_CLIENT_ID}&redirect_uri=${redirectUrl}`
    );
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Connect with your github account</h1>
        <button onClick={handleLoginWithGithub}>Login with github</button>
      </main>
    </>
  );
};

export default Home;
